/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export { GameContract__factory } from "./GameContract__factory";
export { Lock__factory } from "./Lock__factory";
