/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { GameContract } from "./GameContract";
export type { Lock } from "./Lock";
export * as factories from "./factories";
export { GameContract__factory } from "./factories/GameContract__factory";
export type { IGameContract } from "./interfaces/IGameContract";
export { IGameContract__factory } from "./factories/interfaces/IGameContract__factory";
export { Lock__factory } from "./factories/Lock__factory";
